name: Build and push docker image to docker hub

on: push
jobs:
  build:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: docker build -f Dockerfile . -t nirmalyax/GitReact:latest && echo 'dckr_pat_p7Q4i20eKugIYxFja2hiNrDT0NY' | docker login -u 'nirmalyamondal' --password-stdin && docker push nirmalyamondal/GitReact:latest
