name: Build and push docker image to docker hub

on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    
jobs:
  build:
    name: Push Docker image to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo 'dckr_pat_p7Q4i20eKugIYxFja2hiNrDT0NY' | docker login -u 'nirmalyamondal' --password-stdin 
        
      - name: Build Docker image
        run: docker build -f Dockerfile . -t nirmalyamondal/portfolio:latest 

      - name: Push Docker image
        run: docker push nirmalyamondal/portfolio:latest
        
